name: crmapp

services:
  crm-app:
    build:
      context: .
    container_name: crm-app
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_BASE}
      - APP_URL=${APP_URL}
      - APP_PORT=${APP_PORT:-3000}
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - .:/app
      - crm_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  crm_node_modules:

networks:
  crm-network:
    driver: bridge
